# Please implement your Makefile rules and targets below.
# Customize this file to define how to build your project.

all: compile

compile:
	g++ -g -Wall -Weffc++ -std=c++11 -o ./bin/simulation src/* -Iinclude

 
